# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc44fb6113a727f9502f8d1de2c58bc35a69890959123261d55e28ff2ab9de863bed4a6bc625e8e273ba7c8bd7ff4984e536f9126b967208c4a6af33d65bf488

test:
  secret_key_base: 7c44c090f17ef44a553d27fc6fd65c4a8f222875e11c869b22ecaa93b3edc31b91a9d774f115ec5450e7c30dcae2ff505b3b2a8c0771365eaf8795432f259018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
